package com.example.cardiaccorner;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

/**
 * This page is to handle the event handling of the bt_connect_info.xml
 * layout.
 *
 * @Author: Casciano
 */
public class BluetoothConnectInfo extends AppCompatActivity {
    TextView infoBox;
    Button nextBtn;

    /**
     * This is a generic function, autogenerated by Android studio
     * onCreate() is part of the Activity lifecycle, please check Android
     * documentation for position.
     * @param savedInstanceState
     */
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.bt_connect_info_screen); //Find the layout

        //Find the elements needed within the layout
        infoBox = (TextView) findViewById(R.id.infobox);
        nextBtn = (Button) findViewById(R.id.nextBtn);

        //Create the onClick listener for the nextBtn
        nextBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //Start up the BluetoothConnectInfo Activity
                Intent i = new Intent(BluetoothConnectInfo.this, BluetoothCommunicationInfo.class);
                startActivity(i);
            }
        });
    }
}
