package com.example.cardiaccorner;

/**
 * This class is to store an integer index as a result of a HTTP Response
 * which is to delete the logs
 *
 * @Author David Casciano
 */
public class DeleteLogResponse {
    private int index;

    //Autogenerated getter and setter due to it being a private int
    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }
}
