package com.example.cardiaccorner;

/**
 * This is the login response class, each private variable corresponds to the
 * body of the login response. Retrofit2 will then use the getter and setters
 * to populate the private variables
 *
 * @Author: David Casciano
 */
public class LoginResponse {
    //Private data fields that match the body of the response
    private String accessToken;
    private String refreshToken;
    private String email;

    /**
     * Autogenerated getters and setters for the private variables
     */
    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public String getRefreshToken() {
        return refreshToken;
    }

    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
