package com.example.cardiaccorner;

/**
 * This is the login request. You will make this when attempting to login.
 * This is because Retrofit2 and the Userservice requires a class with match variables
 * of the request body.
 *
 * @Author: David Casciano
 */
public class LoginRequest {
    //These must match the request body
    private String username;
    private String password;

    /**
     * Autogenerated getters and setters due to private variables
     */
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
