package com.example.cardiaccorner;

/**
 * LogoutResponse is a class needed by Retrofit2 to capture the response
 * of the Logout
 * @Author: David Casciano
 */
public class LogoutResponse {
    private String token; //This is the string value of the token deleted

    /**
     * Autogenerated getter and setters
     * @return
     */
    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }
}
